(*let connection ~in_memory conninfo =*)
(*  let db =*)
(*    match in_memory with*)
(*    | true -> Sqlite3.db_open ~mode:`NO_CREATE ~mutex:`FULL ":memory:"*)
(*    | false -> Sqlite3.db_open ~mode:`NO_CREATE ~mutex:`FULL conninfo*)
(*  in*)
(*  let query ~connection ~params ~query ~row_limit =*)
(*    Ok (Bytes.of_string "hello")*)
(*  in*)
(*  Ok (Connection.make_connection db query)*)
