name: Generate and publish docs

on:
  release:
    types: [created]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v4
      - name: Set-up OCaml ${{ matrix.ocaml-compiler }}
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: "5.1"
      - run: opam install . --deps-only --with-test
      - run: opam install dune odoc
      - name: Generate docs
        run: opam exec -- dune build @doc
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_build/default/_doc/_html
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
